♻  Move to native ESM
At the moment we have some errors in queue API, admin and editor when
moving to node 24.1.0:
```
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at qo (/app/node_modules/esm/esm.js:1:223175)
    at Uo (/app/node_modules/esm/esm.js:1:222896)
    at $o (/app/node_modules/esm/esm.js:1:224488)
    at wu (/app/node_modules/esm/esm.js:1:227324)
    at Eu (/app/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/app/node_modules/esm/esm.js:1:295976)
    at n (/app/node_modules/esm/esm.js:1:279589)
    at Object.<anonymous> (/app/node_modules/@reedsy/express-ws/index.js:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
```

Changing to export esm natively seems to fix the issue.